### ISSUE TITLE
URLQuery Analyzer

### ISSUE THREAD

**Issue by saadkadhi** [TheHive-Project/Cortex-Analyzers#18]
### Request Type
Analyzer

### Work Environment
NA

### Analyzer Description
Create an analyzer which can submit a URL to [URLQuery](http://urlquery.net/) for profiling.

**Comment by saadkadhi** [comment]
@3c7 offered to implement it.

**Comment by 3c7** [comment]
Well, totally forgot about this one. Asked URLQuery today if they provide access to their API (there seems to be some kind of public API, but it's not documented). If there's no API to use, I'd skip this analyzer because there are enough analyzers capable of getting information about urls and scraping the website for results is not that funny.

**Comment by 3c7** [comment]
URLQuery people are working on a new front- and backend with a new API.

**Comment by saadkadhi** [comment]
@3c7 any update on this front?

**Comment by 3c7** [comment]
Contacted the URLQuery team.

**Comment by Vince147** [comment]
Check Urlscan.io, they got a public API and it very easy to use.

**Comment by Vince147** [comment]
I will create an issue for creating urlscan analyser.

**Comment by 3c7** [comment]
Still no answer from the team. As @Vince147 creates an analyzer for urlscan.io, this can be closed (@saadkadhi).
