### ISSUE TITLE
New Analyzer: hashdd

### ISSUE THREAD

**Issue by iosonogio** [TheHive-Project/Cortex-Analyzers#282]
New Analyzer for hashdd, to check for known good hashes

### Request Type
Analyzer

### Description
Working on a new analyzer to check hashes against the hashdd service https://www.hashdd.com/

**Comment by iosonogio** [comment]
Regarding the max_tlp, does it suffice to configure it in the json or does it need to be enforced in the Anlayzer class? I assumed it was enough to have it in the json like this:

```
    "config": {
        "check_tlp": true,
        "max_tlp": 2
    },
```

Since it wasn't being enforced apparently, I committed a "check_tlp: false" for the moment.

**Comment by saadkadhi** [comment]
Hi @iosonogio,

The TLP must not be included in the JSON file anymore, since Cortex 2. The howto documentation is outdated. Sorry for that. Please take a look at the existing JSON files for reference. For example [https://github.com/TheHive-Project/Cortex-Analyzers/tree/master/analyzers/VirusTotal](https://github.com/TheHive-Project/Cortex-Analyzers/tree/master/analyzers/VirusTotal).

**Comment by iosonogio** [comment]
Hi @saadkadhi , many thanks for clarification, I've just pushed my modifications  to be reviewed. Thank you and sorry about that.

**Comment by iosonogio** [comment]
done, thank you :)
