### ISSUE TITLE
[Bug] FireHOLBlocklists No such file or directory

### ISSUE THREAD

**Issue by asucrews** [TheHive-Project/Cortex-Analyzers#707]
**Describe the bug**

after configure path to blocklist and running a analysis on ip. i get the blow error 

{
  "errorMessage": "Traceback (most recent call last):\n  File \"FireHOLBlocklists/firehol_blocklists.py\", line 146, in <module>\n    FireholBlocklistsAnalyzer().run()\n  File \"FireHOLBlocklists/firehol_blocklists.py\", line 30, in __init__\n    os.mkdir(self.path, 0o0700)\nFileNotFoundError: [Errno 2] No such file or directory: '/etc/firehol/ipsets/'\n",
  "input": null,
  "success": false
}

**To Reproduce**
1. set path for firehol blocklist
2. create new analysis

**Expected behavior**

Matches on firehol blacklist

**Complementary information**
If applicable, add screenshots and any additional information that might help explain your problem.

{
  "errorMessage": "Traceback (most recent call last):\n  File \"FireHOLBlocklists/firehol_blocklists.py\", line 146, in <module>\n    FireholBlocklistsAnalyzer().run()\n  File \"FireHOLBlocklists/firehol_blocklists.py\", line 30, in __init__\n    os.mkdir(self.path, 0o0700)\nFileNotFoundError: [Errno 2] No such file or directory: '/etc/firehol/ipsets/'\n",
  "input": null,
  "success": false
}

**Work environment**
 - Client OS:   windows
- Server OS: ubuntu 18.04
 - Browse type and version:
- Cortex version: 3.0.1-2
 - Cortex Analyzer/Responder name: FireHOLBlocklists_2_0
- Cortex Analyzer/Responder version: lastest

**Possible solutions**
If applicable, indicate possible solutions to the problem.

Not sure if there way to import folder in docker container or docker need pull the blocklist in to it

**Additional context**

**Comment by garanews** [comment]
You can pull inside the docker or you can pull outside and then mount a volume to tell cortex where are the files.

**Comment by garanews** [comment]
Hi @asucrews, was you able to run this Analyzer?

**Comment by asucrews** [comment]
Sorry, i am noob to docker. so i am unsure how to implement the suggested changes.

**Comment by garanews** [comment]
Hi @asucrews , do you have in your docker-compose.yml some volume regarding cortex image such as the config file or cortex-analyzers folder?
![image](https://user-images.githubusercontent.com/16938405/77554935-fdd63a80-6eb6-11ea-8bed-f9aacf8d3cd1.png)

So for example I just did:
```
cd /opt
git clone https://github.com/firehol/blocklist-ipsets
```

then edit the docker-compose in this way:

![Cattura](https://user-images.githubusercontent.com/16938405/77555633-c451ff00-6eb7-11ea-9aa6-2cd57f37539e.PNG)

in order to map the folder outside the container.
Then rebuild the container with
`docker-compose up
` 

and sed the path in firehol analyzer:
![image](https://user-images.githubusercontent.com/16938405/77555849-08450400-6eb8-11ea-841f-ad3da4b0be61.png)



And finally execute the analyzer, you see first attempt without correct setting and second attempt working:
![image](https://user-images.githubusercontent.com/16938405/77556073-4cd09f80-6eb8-11ea-84a2-26b7694a5b05.png)




Let me know if something is not clear or need further help.

**Comment by garanews** [comment]
@asucrews does it work?

**Comment by asucrews** [comment]
This could work, but i installed cortex via deb and the Analyzer are docker method and i don't have the docker-compose to mess with.

**Comment by garanews** [comment]
You can create the volume also with docker, have a look here: http://dockerlabs.collabnix.com/beginners/volume/creating-volume-mount-from-dockercli.html

**Comment by garanews** [comment]
Going to close it, feel free to reopen if have other issues.

**Comment by buzzdeee** [comment]
I do have the very same issue, running cortex 3.1.0 installed ubuntu package, and the analyzers as docker images.
I followed example here to create volume and git cloned the blocklists, 
http://dockerlabs.collabnix.com/beginners/volume/creating-volume-mount-from-dockercli.html

However, when the analyzer runs, I get 
```

{
  "hits": [],
  "count": 0
}
```

as the docker image doesn't mount it. Looking at the code, i guess that's expected when the analyzer doesn't find any of the iplist or netlist files. 

As I run the cortex not as a docker container, there's no docker-compose to tweak.

I guess I'm missing the last step, wonder how to tell cortex to use/mount the given volume when starting up the analyzer. Any clue?
