### ISSUE TITLE
Use APIv2 in Onyphe analyers

### ISSUE THREAD

**Issue by jeromeleonard** [TheHive-Project/Cortex-Analyzers#736]
As published on https://www.onyphe.io/blog/newsletter-20201-apiv2-new-pricing-and-new-web-search-features/  APIv1 of Onyphe is reaching EoL (July 2020). 
@Pierre-Baudry do you have plan to upgrade Onyphe Analyzers and support APIv2  ?

**Comment by onyphe** [comment]
Hello,

furthermore, your current implementation relies on Simple API. We suggest you use the Summary API so you can pivot on data based on the following fields:

- ip
- domain
- hostname

And you will get all categories of information in just one Summary API query instead of multiple Simple API queries.

Feel free to contact us at contact at onyphe dot io in case you need help on this subject.

Best regards,

**Comment by dadokkio** [comment]
I was able to update the code to use the summary and v2 api.
I just have some doubts regarding taxonomies. 
If I keep the same approach with summary I obtain 5/10 taxonomies for each analysis.

Eg with some style changes because render was difficult to use
![image](https://user-images.githubusercontent.com/355183/79438015-445d1780-7fd3-11ea-9115-c6a6350bd5bd.png)

I've no idea if all of them are useful or if we can check only threatlist and move the other info in long template. Any tought?

**Comment by dadokkio** [comment]
I added a "verbose_taxonomies" flag in conf that permit you to keep the old approach [1 object] or to just have the threat count [2 object]

![image](https://user-images.githubusercontent.com/355183/79443862-b127e000-7fda-11ea-921c-037631ad2675.png)

**Comment by dadokkio** [comment]
merging all long templates into one.. this is the result
![image](https://user-images.githubusercontent.com/355183/79448220-55ad2080-7fe1-11ea-9b42-2e7b9f497157.png)

**Comment by onyphe** [comment]
This report view looks really good. You made an awesome work!
