### ISSUE TITLE
[FR] Splunk search analyzer

### ISSUE THREAD

**Issue by horent135** [TheHive-Project/Cortex-Analyzers#791]
What happen to the Splunk search analyzer?  It was part of the analyzer in the older version and now it is completely remove.

**Comment by dadokkio** [comment]
I don't remember any splunk analyzer directly in the list of available ones.
There are some pulls available #534 and #142 but both of them have not been merged yet.

In my opinion an analyzer for software like splunk (or elastic for example) it's difficult because it can be done in a lot of different ways depending on each requirements.

If you used on of them in the past and you want it merged please comment in the relative pull request and we'll take care of testing it and having it merged.
