### ISSUE TITLE
[OSCD Initiative] Develop Responder for Azure Active Directory

### ISSUE THREAD

**Issue by yugoslavskiy** [TheHive-Project/Cortex-Analyzers#858]
**Feature description**

Responder for [Azure Active Directory (AAD)](https://azure.microsoft.com/en-us/services/active-directory/) that would be able to execute the following Response Actions:

- [RA4601](https://atc-project.github.io/atc-react/Response_Actions/RA_4601_revoke_authentication_credentials/): Revoke authentication credentials (API tokens)

**Describe the solution you'd like**

This could be done via [Revoke-AzureADUserAllRefreshToken](https://docs.microsoft.com/en-us/powershell/module/azuread/revoke-azureaduserallrefreshtoken?view=azureadps-2.0) cmdlet.

**Comment by Dmweiner** [comment]
I am going to attempt to tackle this using the Graph API: POST /users/{id | userPrincipalName}/revokeSignInSessions.

**Comment by Dmweiner** [comment]
So I've written the responder python script, json config file, and requirements.txt. I'm trying to import the responder into my cortex VM and I am able to get the responder to show up in the web gui, but the config never shows up. Is there something I'm missing?

**Comment by nadouani** [comment]
Hello @Dmweiner what do you mean by `but the config never shows up`? It is it the responder enable modal that doesn't show the configuration form? or the `Responder Configuration` tab doesn't list your responder?

Can you share the .json file?

**Comment by Dmweiner** [comment]
Hi @nadouani , appreciate the help. 

After adding the path of the responder python code, json service file, and requirements.txt to the cortex config, the json configuration settings for the responder don't show up in the configuration form or in the responder configuration page.

![image](https://user-images.githubusercontent.com/72239832/95663673-3cf47200-0b0f-11eb-8c1c-e3cf766bb9bc.png)
![image](https://user-images.githubusercontent.com/72239832/95663684-4da4e800-0b0f-11eb-918f-25fc74a26ff6.png)
![image](https://user-images.githubusercontent.com/72239832/95663697-5d243100-0b0f-11eb-91e1-9f5390fb0a3b.png)

[AzureTokenRevoker.zip](https://github.com/TheHive-Project/Cortex-Analyzers/files/5359890/AzureTokenRevoker.zip)

**Comment by nadouani** [comment]
How did you configure that in Cortex config file? How do you tell Cortex about your responder?

Your responder's config file looks correct. I'll try it and let you know.

**Comment by nadouani** [comment]
Yeah, after some checking, there is a parsing error on the last configuration items. type `list` is not valid. The `users` configuration items needs to have a `string` type instead of `list`.

<img width="897" alt="Screenshot 2020-10-10 at 22 27 08" src="https://user-images.githubusercontent.com/21827/95664395-c4f66e00-0b47-11eb-83d8-be015156fcd6.png">

**Comment by Dmweiner** [comment]
That is extremely helpful! Thanks!

**Comment by Dmweiner** [comment]
@nadouani Sorry to eat up your time, but what is the easiest way to test a responder? I have something written that I'm sure has some issues I need to iron out but I have not had luck running it.

Using a configured training VM, I'm having issues with getting the hive to see enabled responders in a linked cortex instance.

I'm also having trouble using the utility script analyzer-runlocal to test the responder because I don't know what the format of a job file should look like.

Any pointers on my approaches to debugging the responder?
[AzureTokenRevoker Complete.zip](https://github.com/TheHive-Project/Cortex-Analyzers/files/5361454/AzureTokenRevoker.Complete.zip)

**Comment by nadouani** [comment]
@Dmweiner can you put your responder on a github repository so I can help you review it? You seem to have a typo in your `dataListType`: (`"thehive:case_artifact:"` has an extra `:` and is not valid, so TheHive cannot see it)

**Comment by nadouani** [comment]
The `operations` function is also invalid, since it has to return an array of operations. You can double check other responders to see how it works

**Comment by Dmweiner** [comment]
Sure thing, it will take a minute since I am new to github. I'll make sure to upload the most recent json file as you found that data type problem earlier this weekend :).

**Comment by Dmweiner** [comment]
@nadouani [See uploaded repositories here](https://github.com/Dmweiner/Cortex-Analyzers/tree/master/responders/AzureTokenRevoker)

**Comment by nadouani** [comment]
Hello @Dmweiner here are my comments:
- the responder should be used on `thehive:case_artifact` only (update the ` dataTypeList` in the json definition file)
- you need to check the observable's `dataType` using `data.dataType` (the responder will receive the user email as the data of the observable data). I would check for `data.dataType == "mail"`
- I'm not sure that adding a tag including a timestamp is a good idea, because it will generate a significant number of distinct tags

**Comment by yugoslavskiy** [comment]
Hello @Dmweiner! Sorry for the delayed response, we still finalizing OSCD-related PRs in the other projects. 
I think you can return a simple success message (: 
Could you please create PR so we could proceed with discussion there, reviewing the code?
Thank you!

**Comment by Dmweiner** [comment]
Sure thing, will do it now!

**Comment by 2Wanderer** [comment]
Hi,  i realy like to leverage this responder but it looks like i'm also missing the users field: 

![image](https://user-images.githubusercontent.com/85965392/131477689-10f393a0-0ed3-4bb4-abfb-8d11a3f33b77.png)

the error it throws after running:
![image](https://user-images.githubusercontent.com/85965392/131477890-b7806a42-9380-43c1-a2a9-c7a62cb7704a.png)

I'm using the docker neurons
